### ISSUE TITLE
Duplicated utils code

### ISSUE THREAD

**Issue by michelole** [microsoft/dstoolkit-mlops-base#55]
Some of the [`src/utils.py` code](https://github.com/microsoft/dstoolkit-mlops-base/blob/main/src/utils.py) seems to be duplicated inside the `operations` folder:
- [`retrieve_workspace`](https://github.com/microsoft/dstoolkit-mlops-base/blob/main/operation/execution/utils/workspace.py#L11)
- [`get_dataset`](https://github.com/microsoft/dstoolkit-mlops-base/blob/main/operation/execution/utils/dataset.py#L40)

This is a bit confusing when deploying the template.

**Comment by FlorianPydde** [comment]
Michel you are absolutely right.  There are nevertheless slight differences in the code logic for *retrieve_workspace* for instance. 
When we run code from the _operation_ folder, we assume the code will be run in a devops pipeline, which means we will use Service Principals to connect to the AML workspace. Whereas, when running the code from _src_, the scripts will either be run locally  or on a experiment run. 

There was a similar discussion [here](https://github.com/microsoft/dstoolkit-mlops-base/discussions/41). The problem is not so straightforward to solve but we are eager to get your inputs :smiley: Do you have any suggestions ?

**Comment by mariamedp** [comment]
I agree as well. The main reason that's preventing us from putting everything together is that only the `src/` folder is uploaded to the compute cluster for execution during training/batch inference, and hence we need some AML utilities there. Maybe we can look at simplifying `src/utils.py` at maximum? And/or change the function names to make them more descriptive of the differences?

**Comment by michelole** [comment]
Since this also seems to be duplicated among templates (and potentially among their implementations), I'd favor moving this upstream.

Maybe we should then keep the discussion on the linked thread? Tentatively closing then.

**Comment by michelole** [comment]
If there's a decision *not* to upstream it, we could explore removing the duplicate at least _in this repo_ by:
1. declaring and building a package with all "utils" code
2. publishing it via [a private Python package](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-use-private-python-packages)
3. installing it via pip/conda in the remote compute instance.

**Comment by FlorianPydde** [comment]
The private package option would be a good alternative to reduce code duplication. Nevertherless, there is work in progress for the next release of the aml sdk (here an example regarding pipelines: [azureml-previews]( https://github.com/Azure/azureml-previews/tree/main/previews/pipeline)s) which will probably require some adjustments to the solution. Hence, I would suggest keeping it simple and accessible (vs a package) even though it means having some duplicated code.
